import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/componentes/card.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  
   /* fetch("https://rickandmortyapi.com/api")
    .then(response => console.log("Se cumplió:" + response))
    .catch(reason => console.log("No se cumplió:" + reason))*/
  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       
      <Card imagen="https://rickandmortyapi.com/api/character/avatar/126.jpeg"
      name="Fleeb"></Card>

      </main>
    </>
  )
}
